---
configRoots:
- extension:
    groupId: "com.digibel"
    artifactId: "testcontainers-gotenberg"
    name: "Testcontainers Gotenberg"
    nameSource: "EXTENSION_METADATA"
    detected: true
  prefix: "quarkus.gotenberg"
  topLevelPrefix: "quarkus.gotenberg"
  items:
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "enabled"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.enabled"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_ENABLED"
    type: "boolean"
    phase: "BUILD_TIME"
    typeDescription: "boolean"
    defaultValue: "true"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "imageName"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.image-name"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_IMAGE_NAME"
    type: "java.lang.String"
    phase: "BUILD_TIME"
    typeDescription: "string"
    defaultValue: "gotenberg/gotenberg:8"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "shared"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.shared"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_SHARED"
    type: "boolean"
    phase: "BUILD_TIME"
    typeDescription: "boolean"
    defaultValue: "true"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "serviceName"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.service-name"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_SERVICE_NAME"
    type: "java.lang.String"
    phase: "BUILD_TIME"
    typeDescription: "string"
    defaultValue: "gotenberg"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "port"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.port"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_PORT"
    type: "java.lang.Integer"
    phase: "BUILD_TIME"
    typeDescription: "int"
    optional: true
  qualifiedNames:
  - "com.digibel.testcontainers.gotenberg.runtime.GotenbergBuildTimeConfig"
- extension:
    groupId: "com.digibel"
    artifactId: "testcontainers-gotenberg"
    name: "Testcontainers Gotenberg"
    nameSource: "EXTENSION_METADATA"
    detected: true
  prefix: "quarkus.gotenberg.devservices"
  topLevelPrefix: "quarkus.gotenberg"
  items:
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "enabled"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.enabled"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_ENABLED"
    type: "boolean"
    phase: "BUILD_TIME"
    typeDescription: "boolean"
    defaultValue: "true"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "imageName"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.image-name"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_IMAGE_NAME"
    type: "java.lang.String"
    phase: "BUILD_TIME"
    typeDescription: "string"
    defaultValue: "gotenberg/gotenberg:8"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "shared"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.shared"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_SHARED"
    type: "boolean"
    phase: "BUILD_TIME"
    typeDescription: "boolean"
    defaultValue: "true"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "serviceName"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.service-name"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_SERVICE_NAME"
    type: "java.lang.String"
    phase: "BUILD_TIME"
    typeDescription: "string"
    defaultValue: "gotenberg"
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceType: "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
    sourceElementName: "port"
    sourceElementType: "METHOD"
    path: !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty$PropertyPath>
      property: "quarkus.gotenberg.devservices.port"
      environmentVariable: "QUARKUS_GOTENBERG_DEVSERVICES_PORT"
    type: "java.lang.Integer"
    phase: "BUILD_TIME"
    typeDescription: "int"
    optional: true
  qualifiedNames:
  - "com.digibel.testcontainers.gotenberg.runtime.GotenbergDevServicesConfig"
